config/routes.rb
Rails.application.routes.draw do
  #search with(OUT) elasticsearch
  get 'search', to: 'search#search', defaults: {format: :json}

  resources :recipes, only: [:index, :show, :create, :update, :destroy], defaults: {format: :json}
  resources :shopping_lists, only: [:index, :show, :create, :update, :destroy], defaults: {format: :json}
  resources :shopping_list_items, only: [:create, :update, :destroy], defaults: {format: :json}
  post 'shopping_list_items/bulk', to: 'shopping_list_items#create_from_recipe' # for bulk creation of items
  resources :ingredients, only: [:create, :update, :destroy], defaults: {format: :json}

  root 'welcome#index'
  get '*path', to: 'welcome#index'
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients

  def self.search(query)
    Recipe.where("name LIKE ? or url LIKE ? or tags LIKE ? or notes LIKE ?",
    "%#{query}%","%#{query}%","%#{query}%","%#{query}%")
  end

end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
  has_many :shopping_list_items

  def add_recipe(recipe)
    recipe.ingredients.each do |ingredient|
      self.shopping_list_items.create(name: ingredient.name)
    end
  end
end

app/models/shopping_list_item.rb
class ShoppingListItem < ActiveRecord::Base
  belongs_to :shopping_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      @recipe = @ingredient.recipe
      render 'recipes/show'
    else
      render json: @ingredient.errors.full_messages, status: 422
    end
  end

  def update
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.update(ingredient_params)
      @recipe = @ingredient.recipe
      render 'recipes/show'
    else
      render json: @ingredient.errors.full_messages, status: 422
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    @recipe = @ingredient.recipe
    render 'recipes/show'
  end

  private
    def ingredient_params
      params.require(:ingredient).permit(:name, :recipe_id)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
      @recipes = Recipe.all.includes(:ingredients)
      # render json: @recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    # render json: @recipe
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      # render json: @recipe
      render :show
    else
      render json: @recipe.errors.full_messages, status: 422
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      # render json: @recipe
      render :show
    else
      render json: @recipe.errors.full_messages, status: 422
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    render json: @recipe
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :url, :entree, :soup, :salad, :dessert, :appetizer, :tags, :notes)
    end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @recipes = []
    else
      @recipes = Recipe.search(params[:q]).includes(:ingredients)
    end
    render 'recipes/index'
  end
end

app/controllers/shopping_list_items_controller.rb
class ShoppingListItemsController < ApplicationController
  def create
    @shopping_list_item = ShoppingListItem.new(shopping_list_item_params)
    if @shopping_list_item.save
      @shopping_list = @shopping_list_item.shopping_list
      render 'shopping_lists/show'
    else
      render json: @shopping_list_item.errors.full_messages, status: 422
    end
  end

  def update
    @shopping_list_item = ShoppingListItem.find(params[:id])
    if @shopping_list_item.update(shopping_list_item_params)
      @shopping_list = @shopping_list_item.shopping_list
      render 'shopping_lists/show'
    else
      render json: @shopping_list.errors.full_messages, status: 422
    end
  end

  def destroy
    @shopping_list_item = ShoppingListItem.find(params[:id])
    if @shopping_list_item.destroy
      @shopping_list = @shopping_list_item.shopping_list
      render 'shopping_lists/show'
    else
      render json: @shopping_list_item.errors.full_messages, status: 422
    end
  end

  def create_from_recipe
    @recipe = Recipe.find(params[:recipe_id])
    bulk_shopping_list_item_params = @recipe.ingredients.map do |ingredient|
      {name: ingredient.name, shopping_list_id: params[:shopping_list_id], recipe_id: params[:recipe_id]}
    end
    if ShoppingListItem.create(bulk_shopping_list_item_params)
      @shopping_list = ShoppingList.find(params[:shopping_list_id])
      render 'shopping_lists/show'
    else
      render json: @shopping_list_items.errors.full_messages, status: 422
    end
  end

  def shopping_list_item_params
    params.require(:shopping_list_item).permit(:name, :shopping_list_id, :recipe_id, :done)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @shopping_lists = ShoppingList.all
    # render json: @shopping_lists
  end

  def show
    @shopping_list = ShoppingList.find(params[:id])
    # render json: @shopping_list
  end

  def create
    @shopping_list = ShoppingList.new(name: "new list")
    if @shopping_list.save
      # render json: @shopping_list
      render :show
    else
      render json: @shopping_list.errors.full_messages, status: 422
    end
  end

  def update
    @shopping_list = ShoppingList.find(params[:id])
    if @shopping_list.update(shopping_list_params)
      # render json: @shopping_list
      render :show
    else
      render json: @shopping_list.errors.full_messages, status: 422
    end
  end

  def destroy
    @shopping_list = ShoppingList.find(params[:id])
    if @shopping_list.destroy
      render json: @shopping_list
    else
      render json: @shopping_list.errors.full_messages, status: 422
    end
  end

  private
  def shopping_list_params
    params.require(:shopping_list).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/shopping_list_items_helper.rb
module ShoppingListItemsHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chezjocay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %> prohibited
        this recipe from being saved:
      </h2>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :type %><br>
    <%= f.check_box :entree %> <%= label_tag(:Entree, "Entree") %>
    <%= f.check_box :soup %> <%= label_tag(:Soup, "Soup") %>
    <%= f.check_box :salad %> <%= label_tag(:Salad, "Salad") %>
    <%= f.check_box :dessert %> <%= label_tag(:Dessert, "Dessert") %>
    <%= f.check_box :appetizer %> <%= label_tag(:Appetizer, "Appetizer") %>
  </p>

  <p>
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </p>

  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>All recipes</h1>

<p>
<%= link_to 'New recipe', new_recipe_path %>
<%= link_to 'Search recipes', search_path %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Tags</th>
    <th>Notes</th>
  </tr>

  <% @recipes.each do |recipe| %>
    <tr>
      <td><a href="<%= recipe.url %>"><%= recipe.name %></a></td>
      <td>
        <% if recipe.entree %>
          Entree
        <% end %>
        <% if recipe.soup %>
          Soup
        <% end %>
        <% if recipe.salad %>
          Salad
        <% end %>
        <% if recipe.dessert %>
          Dessert
        <% end %>
        <% if recipe.appetizer %>
          Appetizer
        <% end %>
      </td>
      <td><%= recipe.tags %></td>
      <td><%= recipe.notes %></td>

      <td><%= link_to 'Show', recipe_path(recipe) %></td>
      <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
      <td><%= link_to 'Destroy', recipe_path(recipe),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p>
  <strong>Name:</strong>
  <a href="<%= @recipe.url %>"><%= @recipe.name %></a>
</p>

<p>
  <strong>Type:</strong>
  <% if @recipe.entree %>
    Entree
  <% end %>
  <% if @recipe.soup %>
    Soup
  <% end %>
  <% if @recipe.salad %>
    Salad
  <% end %>
  <% if @recipe.dessert %>
    Dessert
  <% end %>
  <% if @recipe.appetizer %>
    Appetizer
  <% end %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @recipe.tags %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @recipe.notes %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/search/search.html.erb
<h1>Recipes Search</h1>

<%= link_to 'See all', recipes_path %>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @recipes.each do |recipe| %>
    <li>
      <h3>
        <%= link_to recipe.name, controller: "recipes", action: "show", id: recipe.id %>
      </h3>
      <p><i><%= recipe.tags %></i></p>
      <p><%= recipe.notes %></p>
    </li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<div id="luv-you-joc"></div>